import AuthStoreInstance from "./Auth";
import StorageStoreInstance from "./Storage";
import TypefaceStoreInstance from "./Typefaces";
import CustomTypefaceStoreInstance from "./CustomTypefaces";
import FontStoreInstance from "./FontsForm";
import FontsInUseStoreInstance from "./FontsInUseForm";
import FontsFeaturedFullScreenStoreInstance from "./FontsFeaturedFullScreenForm";
import FontsFeaturedGridStoreInstance from "./FontsFeaturedGridForm";
import CustomFontsFeaturedFullScreenStoreInstance from "./CustomFontsFeaturedFullScreenForm";
import CustomFontsFeaturedGridStoreInstance from "./CustomFontsFeaturedGridForm";
import BlogStoreInstance from "./BlogForm";
import BlogFeaturedArticlesStoreInstance from "./BlogFeaturedArticlesForm";

export const AuthStore = AuthStoreInstance;
export const TypefaceStore = TypefaceStoreInstance;
export const CustomTypefaceStore = CustomTypefaceStoreInstance;
export const FontStore = FontStoreInstance;
export const FontsInUseStore = FontsInUseStoreInstance;
export const FontsFeaturedFullScreenStore = FontsFeaturedFullScreenStoreInstance;
export const FontsFeaturedGridStore = FontsFeaturedGridStoreInstance;
export const CustomFontsFeaturedFullScreenStore = CustomFontsFeaturedFullScreenStoreInstance;
export const CustomFontsFeaturedGridStore = CustomFontsFeaturedGridStoreInstance;
export const BlogStore = BlogStoreInstance;
export const BlogFeaturedArticlesStore = BlogFeaturedArticlesStoreInstance;
export const StorageStore = StorageStoreInstance;
